// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: pkg/pb/CidrCountryPairs.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CidrCountryPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CidrCountryPair) Reset() {
	*x = CidrCountryPair{}
	mi := &file_pkg_pb_CidrCountryPairs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CidrCountryPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CidrCountryPair) ProtoMessage() {}

func (x *CidrCountryPair) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_CidrCountryPairs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CidrCountryPair.ProtoReflect.Descriptor instead.
func (*CidrCountryPair) Descriptor() ([]byte, []int) {
	return file_pkg_pb_CidrCountryPairs_proto_rawDescGZIP(), []int{0}
}

func (x *CidrCountryPair) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *CidrCountryPair) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type CidrCountryPairs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*CidrCountryPair     `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CidrCountryPairs) Reset() {
	*x = CidrCountryPairs{}
	mi := &file_pkg_pb_CidrCountryPairs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CidrCountryPairs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CidrCountryPairs) ProtoMessage() {}

func (x *CidrCountryPairs) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_CidrCountryPairs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CidrCountryPairs.ProtoReflect.Descriptor instead.
func (*CidrCountryPairs) Descriptor() ([]byte, []int) {
	return file_pkg_pb_CidrCountryPairs_proto_rawDescGZIP(), []int{1}
}

func (x *CidrCountryPairs) GetPairs() []*CidrCountryPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

var File_pkg_pb_CidrCountryPairs_proto protoreflect.FileDescriptor

var file_pkg_pb_CidrCountryPairs_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x43, 0x69, 0x64, 0x72, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x50, 0x61, 0x69, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x49, 0x70, 0x44, 0x61, 0x74, 0x61, 0x22, 0x3f, 0x0a, 0x0f, 0x43, 0x69, 0x64, 0x72, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x61, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69,
	0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x64, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x41, 0x0a, 0x10, 0x43, 0x69, 0x64, 0x72,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x61, 0x69, 0x72, 0x73, 0x12, 0x2d, 0x0a, 0x05,
	0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x49, 0x70,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x69, 0x64, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x42, 0x11, 0x5a, 0x0f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pkg_pb_CidrCountryPairs_proto_rawDescOnce sync.Once
	file_pkg_pb_CidrCountryPairs_proto_rawDescData []byte
)

func file_pkg_pb_CidrCountryPairs_proto_rawDescGZIP() []byte {
	file_pkg_pb_CidrCountryPairs_proto_rawDescOnce.Do(func() {
		file_pkg_pb_CidrCountryPairs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_CidrCountryPairs_proto_rawDesc), len(file_pkg_pb_CidrCountryPairs_proto_rawDesc)))
	})
	return file_pkg_pb_CidrCountryPairs_proto_rawDescData
}

var file_pkg_pb_CidrCountryPairs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_pb_CidrCountryPairs_proto_goTypes = []any{
	(*CidrCountryPair)(nil),  // 0: IpData.CidrCountryPair
	(*CidrCountryPairs)(nil), // 1: IpData.CidrCountryPairs
}
var file_pkg_pb_CidrCountryPairs_proto_depIdxs = []int32{
	0, // 0: IpData.CidrCountryPairs.pairs:type_name -> IpData.CidrCountryPair
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_pb_CidrCountryPairs_proto_init() }
func file_pkg_pb_CidrCountryPairs_proto_init() {
	if File_pkg_pb_CidrCountryPairs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_CidrCountryPairs_proto_rawDesc), len(file_pkg_pb_CidrCountryPairs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_pb_CidrCountryPairs_proto_goTypes,
		DependencyIndexes: file_pkg_pb_CidrCountryPairs_proto_depIdxs,
		MessageInfos:      file_pkg_pb_CidrCountryPairs_proto_msgTypes,
	}.Build()
	File_pkg_pb_CidrCountryPairs_proto = out.File
	file_pkg_pb_CidrCountryPairs_proto_goTypes = nil
	file_pkg_pb_CidrCountryPairs_proto_depIdxs = nil
}
