// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pkg/pb/GeoData.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CIDR string `protobuf:"bytes,1,opt,name=CIDR,proto3" json:"CIDR,omitempty"`
	Geo  *Geo   `protobuf:"bytes,2,opt,name=geo,proto3" json:"geo,omitempty"`
}

func (x *DataItem) Reset() {
	*x = DataItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_GeoData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataItem) ProtoMessage() {}

func (x *DataItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_GeoData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataItem.ProtoReflect.Descriptor instead.
func (*DataItem) Descriptor() ([]byte, []int) {
	return file_pkg_pb_GeoData_proto_rawDescGZIP(), []int{0}
}

func (x *DataItem) GetCIDR() string {
	if x != nil {
		return x.CIDR
	}
	return ""
}

func (x *DataItem) GetGeo() *Geo {
	if x != nil {
		return x.Geo
	}
	return nil
}

type Geo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Continent         *Geo_Continent         `protobuf:"bytes,1,opt,name=continent,proto3" json:"continent,omitempty"`
	Country           *Geo_Country           `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	RegisteredCountry *Geo_RegisteredCountry `protobuf:"bytes,3,opt,name=registered_country,json=registeredCountry,proto3" json:"registered_country,omitempty"`
}

func (x *Geo) Reset() {
	*x = Geo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_GeoData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Geo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geo) ProtoMessage() {}

func (x *Geo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_GeoData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geo.ProtoReflect.Descriptor instead.
func (*Geo) Descriptor() ([]byte, []int) {
	return file_pkg_pb_GeoData_proto_rawDescGZIP(), []int{1}
}

func (x *Geo) GetContinent() *Geo_Continent {
	if x != nil {
		return x.Continent
	}
	return nil
}

func (x *Geo) GetCountry() *Geo_Country {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *Geo) GetRegisteredCountry() *Geo_RegisteredCountry {
	if x != nil {
		return x.RegisteredCountry
	}
	return nil
}

type DataItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Geos []*DataItem `protobuf:"bytes,1,rep,name=geos,proto3" json:"geos,omitempty"`
}

func (x *DataItems) Reset() {
	*x = DataItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_GeoData_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataItems) ProtoMessage() {}

func (x *DataItems) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_GeoData_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataItems.ProtoReflect.Descriptor instead.
func (*DataItems) Descriptor() ([]byte, []int) {
	return file_pkg_pb_GeoData_proto_rawDescGZIP(), []int{2}
}

func (x *DataItems) GetGeos() []*DataItem {
	if x != nil {
		return x.Geos
	}
	return nil
}

type Geo_Names struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	De    string `protobuf:"bytes,1,opt,name=de,proto3" json:"de,omitempty"`
	En    string `protobuf:"bytes,2,opt,name=en,proto3" json:"en,omitempty"`
	Es    string `protobuf:"bytes,3,opt,name=es,proto3" json:"es,omitempty"`
	Fr    string `protobuf:"bytes,4,opt,name=fr,proto3" json:"fr,omitempty"`
	Ja    string `protobuf:"bytes,5,opt,name=ja,proto3" json:"ja,omitempty"`
	Pt_BR string `protobuf:"bytes,6,opt,name=pt_BR,json=pt-BR,proto3" json:"pt_BR,omitempty"`
	Ru    string `protobuf:"bytes,7,opt,name=ru,proto3" json:"ru,omitempty"`
	Zh_CN string `protobuf:"bytes,8,opt,name=zh_CN,json=zh-CN,proto3" json:"zh_CN,omitempty"`
}

func (x *Geo_Names) Reset() {
	*x = Geo_Names{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_GeoData_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Geo_Names) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geo_Names) ProtoMessage() {}

func (x *Geo_Names) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_GeoData_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geo_Names.ProtoReflect.Descriptor instead.
func (*Geo_Names) Descriptor() ([]byte, []int) {
	return file_pkg_pb_GeoData_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Geo_Names) GetDe() string {
	if x != nil {
		return x.De
	}
	return ""
}

func (x *Geo_Names) GetEn() string {
	if x != nil {
		return x.En
	}
	return ""
}

func (x *Geo_Names) GetEs() string {
	if x != nil {
		return x.Es
	}
	return ""
}

func (x *Geo_Names) GetFr() string {
	if x != nil {
		return x.Fr
	}
	return ""
}

func (x *Geo_Names) GetJa() string {
	if x != nil {
		return x.Ja
	}
	return ""
}

func (x *Geo_Names) GetPt_BR() string {
	if x != nil {
		return x.Pt_BR
	}
	return ""
}

func (x *Geo_Names) GetRu() string {
	if x != nil {
		return x.Ru
	}
	return ""
}

func (x *Geo_Names) GetZh_CN() string {
	if x != nil {
		return x.Zh_CN
	}
	return ""
}

type Geo_Continent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      string     `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	GeonameId uint32     `protobuf:"varint,2,opt,name=geoname_id,json=geonameId,proto3" json:"geoname_id,omitempty"`
	Names     *Geo_Names `protobuf:"bytes,3,opt,name=names,proto3" json:"names,omitempty"`
}

func (x *Geo_Continent) Reset() {
	*x = Geo_Continent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_GeoData_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Geo_Continent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geo_Continent) ProtoMessage() {}

func (x *Geo_Continent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_GeoData_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geo_Continent.ProtoReflect.Descriptor instead.
func (*Geo_Continent) Descriptor() ([]byte, []int) {
	return file_pkg_pb_GeoData_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Geo_Continent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Geo_Continent) GetGeonameId() uint32 {
	if x != nil {
		return x.GeonameId
	}
	return 0
}

func (x *Geo_Continent) GetNames() *Geo_Names {
	if x != nil {
		return x.Names
	}
	return nil
}

type Geo_Country struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GeonameId         uint32     `protobuf:"varint,1,opt,name=geoname_id,json=geonameId,proto3" json:"geoname_id,omitempty"`
	IsInEuropeanUnion bool       `protobuf:"varint,2,opt,name=is_in_european_union,json=isInEuropeanUnion,proto3" json:"is_in_european_union,omitempty"`
	IsoCode           string     `protobuf:"bytes,3,opt,name=iso_code,json=isoCode,proto3" json:"iso_code,omitempty"`
	Names             *Geo_Names `protobuf:"bytes,4,opt,name=names,proto3" json:"names,omitempty"`
}

func (x *Geo_Country) Reset() {
	*x = Geo_Country{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_GeoData_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Geo_Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geo_Country) ProtoMessage() {}

func (x *Geo_Country) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_GeoData_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geo_Country.ProtoReflect.Descriptor instead.
func (*Geo_Country) Descriptor() ([]byte, []int) {
	return file_pkg_pb_GeoData_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Geo_Country) GetGeonameId() uint32 {
	if x != nil {
		return x.GeonameId
	}
	return 0
}

func (x *Geo_Country) GetIsInEuropeanUnion() bool {
	if x != nil {
		return x.IsInEuropeanUnion
	}
	return false
}

func (x *Geo_Country) GetIsoCode() string {
	if x != nil {
		return x.IsoCode
	}
	return ""
}

func (x *Geo_Country) GetNames() *Geo_Names {
	if x != nil {
		return x.Names
	}
	return nil
}

type Geo_RegisteredCountry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GeonameId         uint32     `protobuf:"varint,1,opt,name=geoname_id,json=geonameId,proto3" json:"geoname_id,omitempty"`
	IsInEuropeanUnion bool       `protobuf:"varint,2,opt,name=is_in_european_union,json=isInEuropeanUnion,proto3" json:"is_in_european_union,omitempty"`
	IsoCode           string     `protobuf:"bytes,3,opt,name=iso_code,json=isoCode,proto3" json:"iso_code,omitempty"`
	Names             *Geo_Names `protobuf:"bytes,4,opt,name=names,proto3" json:"names,omitempty"`
}

func (x *Geo_RegisteredCountry) Reset() {
	*x = Geo_RegisteredCountry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_GeoData_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Geo_RegisteredCountry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geo_RegisteredCountry) ProtoMessage() {}

func (x *Geo_RegisteredCountry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_GeoData_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geo_RegisteredCountry.ProtoReflect.Descriptor instead.
func (*Geo_RegisteredCountry) Descriptor() ([]byte, []int) {
	return file_pkg_pb_GeoData_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Geo_RegisteredCountry) GetGeonameId() uint32 {
	if x != nil {
		return x.GeonameId
	}
	return 0
}

func (x *Geo_RegisteredCountry) GetIsInEuropeanUnion() bool {
	if x != nil {
		return x.IsInEuropeanUnion
	}
	return false
}

func (x *Geo_RegisteredCountry) GetIsoCode() string {
	if x != nil {
		return x.IsoCode
	}
	return ""
}

func (x *Geo_RegisteredCountry) GetNames() *Geo_Names {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_pkg_pb_GeoData_proto protoreflect.FileDescriptor

var file_pkg_pb_GeoData_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x47, 0x65, 0x6f, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x49, 0x70, 0x44, 0x61, 0x74, 0x61, 0x22, 0x3d,
	0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x49,
	0x44, 0x52, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x49, 0x44, 0x52, 0x12, 0x1d,
	0x0a, 0x03, 0x67, 0x65, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x49, 0x70,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x6f, 0x52, 0x03, 0x67, 0x65, 0x6f, 0x22, 0x82, 0x06,
	0x0a, 0x03, 0x47, 0x65, 0x6f, 0x12, 0x33, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x49, 0x70, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x47, 0x65, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74, 0x52,
	0x09, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x49, 0x70,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x6f, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x4d, 0x0a, 0x12, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x49, 0x70, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x47,
	0x65, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x11, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65,
	0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x1a, 0x93, 0x01, 0x0a, 0x05, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x66, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x6a, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x6a, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x74, 0x5f, 0x42, 0x52, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x74, 0x2d, 0x42, 0x52, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x75, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x72, 0x75, 0x12, 0x14, 0x0a, 0x05, 0x7a, 0x68, 0x5f, 0x43,
	0x4e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x7a, 0x68, 0x2d, 0x43, 0x4e, 0x1a, 0x67,
	0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x67, 0x65, 0x6f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x67, 0x65, 0x6f, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x27,
	0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x49, 0x70, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x6f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x1a, 0x9d, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x65, 0x6f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x67, 0x65, 0x6f, 0x6e, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x12, 0x2f, 0x0a, 0x14, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x5f, 0x65, 0x75, 0x72, 0x6f,
	0x70, 0x65, 0x61, 0x6e, 0x5f, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x11, 0x69, 0x73, 0x49, 0x6e, 0x45, 0x75, 0x72, 0x6f, 0x70, 0x65, 0x61, 0x6e, 0x55, 0x6e,
	0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x6f, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x73, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x27,
	0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x49, 0x70, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x6f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x1a, 0xa8, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1d,
	0x0a, 0x0a, 0x67, 0x65, 0x6f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x67, 0x65, 0x6f, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x2f, 0x0a,
	0x14, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x5f, 0x65, 0x75, 0x72, 0x6f, 0x70, 0x65, 0x61, 0x6e, 0x5f,
	0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x69, 0x73, 0x49,
	0x6e, 0x45, 0x75, 0x72, 0x6f, 0x70, 0x65, 0x61, 0x6e, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x19,
	0x0a, 0x08, 0x69, 0x73, 0x6f, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x69, 0x73, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x49, 0x70, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x47, 0x65, 0x6f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x05, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x22, 0x31, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12,
	0x24, 0x0a, 0x04, 0x67, 0x65, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x49, 0x70, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x04, 0x67, 0x65, 0x6f, 0x73, 0x42, 0x11, 0x5a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_GeoData_proto_rawDescOnce sync.Once
	file_pkg_pb_GeoData_proto_rawDescData = file_pkg_pb_GeoData_proto_rawDesc
)

func file_pkg_pb_GeoData_proto_rawDescGZIP() []byte {
	file_pkg_pb_GeoData_proto_rawDescOnce.Do(func() {
		file_pkg_pb_GeoData_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_GeoData_proto_rawDescData)
	})
	return file_pkg_pb_GeoData_proto_rawDescData
}

var file_pkg_pb_GeoData_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_pb_GeoData_proto_goTypes = []interface{}{
	(*DataItem)(nil),              // 0: IpData.DataItem
	(*Geo)(nil),                   // 1: IpData.Geo
	(*DataItems)(nil),             // 2: IpData.DataItems
	(*Geo_Names)(nil),             // 3: IpData.Geo.Names
	(*Geo_Continent)(nil),         // 4: IpData.Geo.Continent
	(*Geo_Country)(nil),           // 5: IpData.Geo.Country
	(*Geo_RegisteredCountry)(nil), // 6: IpData.Geo.Registered_country
}
var file_pkg_pb_GeoData_proto_depIdxs = []int32{
	1, // 0: IpData.DataItem.geo:type_name -> IpData.Geo
	4, // 1: IpData.Geo.continent:type_name -> IpData.Geo.Continent
	5, // 2: IpData.Geo.country:type_name -> IpData.Geo.Country
	6, // 3: IpData.Geo.registered_country:type_name -> IpData.Geo.Registered_country
	0, // 4: IpData.DataItems.geos:type_name -> IpData.DataItem
	3, // 5: IpData.Geo.Continent.names:type_name -> IpData.Geo.Names
	3, // 6: IpData.Geo.Country.names:type_name -> IpData.Geo.Names
	3, // 7: IpData.Geo.Registered_country.names:type_name -> IpData.Geo.Names
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_pb_GeoData_proto_init() }
func file_pkg_pb_GeoData_proto_init() {
	if File_pkg_pb_GeoData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_GeoData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_GeoData_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Geo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_GeoData_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_GeoData_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Geo_Names); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_GeoData_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Geo_Continent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_GeoData_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Geo_Country); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_GeoData_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Geo_RegisteredCountry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_GeoData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_pb_GeoData_proto_goTypes,
		DependencyIndexes: file_pkg_pb_GeoData_proto_depIdxs,
		MessageInfos:      file_pkg_pb_GeoData_proto_msgTypes,
	}.Build()
	File_pkg_pb_GeoData_proto = out.File
	file_pkg_pb_GeoData_proto_rawDesc = nil
	file_pkg_pb_GeoData_proto_goTypes = nil
	file_pkg_pb_GeoData_proto_depIdxs = nil
}
