// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: pkg/pb/ip_data.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IpData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IP            string                 `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=Country,proto3" json:"Country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpData) Reset() {
	*x = IpData{}
	mi := &file_pkg_pb_ip_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpData) ProtoMessage() {}

func (x *IpData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_ip_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpData.ProtoReflect.Descriptor instead.
func (*IpData) Descriptor() ([]byte, []int) {
	return file_pkg_pb_ip_data_proto_rawDescGZIP(), []int{0}
}

func (x *IpData) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *IpData) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

var File_pkg_pb_ip_data_proto protoreflect.FileDescriptor

var file_pkg_pb_ip_data_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x69, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x49, 0x70, 0x44, 0x61, 0x74, 0x61, 0x22, 0x32,
	0x0a, 0x06, 0x49, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x42, 0x11, 0x5a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pkg_pb_ip_data_proto_rawDescOnce sync.Once
	file_pkg_pb_ip_data_proto_rawDescData []byte
)

func file_pkg_pb_ip_data_proto_rawDescGZIP() []byte {
	file_pkg_pb_ip_data_proto_rawDescOnce.Do(func() {
		file_pkg_pb_ip_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_ip_data_proto_rawDesc), len(file_pkg_pb_ip_data_proto_rawDesc)))
	})
	return file_pkg_pb_ip_data_proto_rawDescData
}

var file_pkg_pb_ip_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_pb_ip_data_proto_goTypes = []any{
	(*IpData)(nil), // 0: IpData.IpData
}
var file_pkg_pb_ip_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_pb_ip_data_proto_init() }
func file_pkg_pb_ip_data_proto_init() {
	if File_pkg_pb_ip_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_ip_data_proto_rawDesc), len(file_pkg_pb_ip_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_pb_ip_data_proto_goTypes,
		DependencyIndexes: file_pkg_pb_ip_data_proto_depIdxs,
		MessageInfos:      file_pkg_pb_ip_data_proto_msgTypes,
	}.Build()
	File_pkg_pb_ip_data_proto = out.File
	file_pkg_pb_ip_data_proto_goTypes = nil
	file_pkg_pb_ip_data_proto_depIdxs = nil
}
